name: test_sdk

on:
  push:
    branches:
    tags:
  pull_request:
jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.39.0
          go get -u github.com/mattn/goveralls

      - name: test and lint
        run: |
          go test -race -timeout=60s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
          $GITHUB_WORKSPACE/golangci-lint --config ${GITHUB_WORKSPACE}/.golangci.yml run --out-format=github-actions ./...
        working-directory: .
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "America/Chicago"

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        working-directory: .
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}